# Generated by Django 2.0.3 on 2019-08-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('age', models.IntegerField(verbose_name='年纪')),
            ],
        ),
    ]
