# Generated by Django 2.0.3 on 2019-08-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rouya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='remark',
            field=models.CharField(default='33333333333333', max_length=128, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='test',
            name='sex',
            field=models.CharField(default='wwwwwww', max_length=64, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(default=22, verbose_name='年纪'),
        ),
    ]
