# Generated by Django 2.0.3 on 2019-05-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('companyName', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司名')),
                ('remark', models.CharField(blank=True, max_length=16, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('SpeciesName', models.CharField(max_length=16, verbose_name='品种名')),
                ('BirdType', models.CharField(max_length=16, verbose_name='禽类属性')),
                ('Generation', models.CharField(max_length=8, verbose_name='代次')),
                ('Remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
        ),
    ]
