# Generated by Django 2.0.3 on 2019-05-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesinfo',
            name='Remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
    ]
