# Generated by Django 2.0.3 on 2019-05-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0002_auto_20190525_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgenitorIntroduced',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('Year', models.IntegerField(verbose_name='年份')),
                ('WeekNum', models.IntegerField(verbose_name='周度')),
                ('startDate', models.DateField(verbose_name='开始日期')),
                ('endDate', models.DateField(verbose_name='结束日期')),
                ('CompanyId', models.IntegerField(verbose_name='公司名')),
                ('SpeciesId', models.IntegerField(verbose_name='品种')),
                ('RuSheNum', models.IntegerField(verbose_name='入舍量')),
                ('LivePeriod', models.IntegerField(verbose_name='生存周期')),
                ('nGeneration', models.IntegerField(verbose_name='代次')),
                ('nDraftOrOriginal', models.IntegerField(verbose_name='存储类型')),
                ('nBirdsType', models.IntegerField(verbose_name='家禽种类')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
