# Generated by Django 2.0.3 on 2019-05-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0005_auto_20190525_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekStandardTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('Year', models.IntegerField(verbose_name='年份')),
                ('WeekNum', models.IntegerField(verbose_name='周度')),
                ('startDate', models.DateField(verbose_name='开始日期')),
                ('endDate', models.DateField(verbose_name='结束日期')),
                ('siTaoRate', models.FloatField(verbose_name='死淘率')),
                ('ChanDanRate', models.FloatField(verbose_name='产蛋率')),
                ('RuFuZhongDanRate', models.FloatField(verbose_name='入孵种蛋率')),
                ('ShouJingRate', models.FloatField(verbose_name='受精率')),
                ('FuHuaRate', models.FloatField(verbose_name='孵化率')),
                ('JianChuRate', models.FloatField(verbose_name='健雏率')),
                ('SaleRate', models.FloatField(verbose_name='销售率')),
                ('nGeneration', models.IntegerField(verbose_name='代次')),
                ('nBirdsType', models.IntegerField(verbose_name='家禽种类')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
