# Generated by Django 2.0.3 on 2019-05-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0006_weekstandardtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePeriodTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('Year', models.IntegerField(verbose_name='年份')),
                ('WeekNum', models.IntegerField(verbose_name='周度')),
                ('startDate', models.DateField(verbose_name='开始日期')),
                ('endDate', models.DateField(verbose_name='结束日期')),
                ('LivePeriod', models.IntegerField(verbose_name='生存周期')),
                ('nGeneration', models.IntegerField(verbose_name='代次')),
                ('nDraftOrOriginal', models.IntegerField(verbose_name='存储类型')),
                ('nBirdsType', models.IntegerField(verbose_name='家禽种类')),
            ],
        ),
    ]
