# Generated by Django 2.0.3 on 2019-05-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0008_auto_20190526_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStandardTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('nDay', models.IntegerField(verbose_name='日次')),
                ('SiTaoRate', models.FloatField(verbose_name='日度死淘率（%）')),
                ('nBirdsType', models.IntegerField(verbose_name='家禽种类')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
