# Generated by Django 2.0.3 on 2019-05-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0010_wholeparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('BirdName', models.CharField(max_length=8, verbose_name='禽类名称')),
                ('Remark', models.CharField(blank=True, max_length=16, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='WeekCorrectionFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('Year', models.IntegerField(verbose_name='年份')),
                ('WeekNum', models.IntegerField(verbose_name='周度')),
                ('startDate', models.DateField(verbose_name='开始日期')),
                ('endDate', models.DateField(verbose_name='结束日期')),
                ('SiTaoC', models.FloatField(verbose_name='死淘率校正')),
                ('SiTaoCNote', models.CharField(max_length=128, verbose_name='死淘率校正备注')),
                ('ChanDanC', models.FloatField(verbose_name='产蛋率校正')),
                ('ChanDanCNote', models.CharField(max_length=128, verbose_name='产蛋率校正备注')),
                ('RuFuZhongDanC', models.FloatField(verbose_name='入孵种蛋率校正')),
                ('RuFuZhongDanCNote', models.CharField(max_length=128, verbose_name='入孵种蛋率校正备注')),
                ('ShouJingC', models.FloatField(verbose_name='受精率校正')),
                ('ShouJingCNote', models.CharField(max_length=128, verbose_name='受精率校正备注')),
                ('FuHuaC', models.FloatField(verbose_name='孵化率校正')),
                ('FuHuaCNote', models.CharField(max_length=128, verbose_name='孵化率校正备注')),
                ('JianChuC', models.FloatField(verbose_name='健雏率校正')),
                ('JianChuCNote', models.CharField(max_length=128, verbose_name='健雏率校正备注')),
                ('SaleRateC', models.FloatField(verbose_name='销售率校正')),
                ('SaleRateCNote', models.CharField(max_length=128, verbose_name='销售率校正备注')),
                ('nGeneration', models.IntegerField(verbose_name='存储类型')),
                ('nBirdsType', models.IntegerField(verbose_name='家禽种类')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
