# Generated by Django 2.0.3 on 2019-05-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0011_birdstype_weekcorrectionfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearTCJirouParam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('StandardTZ', models.FloatField(verbose_name='标准体重（kg）')),
                ('TuZaiRate', models.FloatField(verbose_name='屠宰率（%）')),
                ('nGeneration', models.IntegerField(verbose_name='存储类型')),
                ('nBirdsType', models.IntegerField(verbose_name='家禽种类')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
