# Generated by Django 2.0.3 on 2019-06-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0013_auto_20190527_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekstandardtable',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='weekstandardtable',
            name='startDate',
        ),
        migrations.AlterField(
            model_name='weekstandardtable',
            name='WeekNum',
            field=models.IntegerField(verbose_name='生产周'),
        ),
    ]
