# Generated by Django 2.0.3 on 2019-06-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0014_auto_20190604_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekstandardtable',
            name='Year',
        ),
    ]
