# Generated by Django 2.0.3 on 2019-06-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0016_weekdatestandard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekDateStandard',
        ),
    ]
