# Generated by Django 2.0.3 on 2019-06-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0017_delete_weekdatestandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDateStandard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('Year', models.IntegerField(verbose_name='年份')),
                ('WeekNum', models.IntegerField(verbose_name='周度')),
                ('startDate', models.DateField(verbose_name='开始日期')),
                ('endDate', models.DateField(verbose_name='结束日期')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
