# Generated by Django 2.0.3 on 2019-06-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0018_weekdatestandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedWay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('feedWayName', models.CharField(max_length=8, verbose_name='饲养方式')),
                ('description', models.CharField(max_length=64, verbose_name='说明')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
