# Generated by Django 2.0.3 on 2019-06-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0019_feedway'),
    ]

    operations = [
        migrations.AddField(
            model_name='progenitorintroduceddetail',
            name='feedWayId',
            field=models.IntegerField(default=1, verbose_name='饲养方式'),
        ),
    ]
