# Generated by Django 2.0.3 on 2019-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0021_auto_20190625_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekstandardtable',
            name='SpeciesId',
            field=models.IntegerField(default=1, verbose_name='品种'),
        ),
        migrations.AddField(
            model_name='weekstandardtable',
            name='feedWayId',
            field=models.IntegerField(default=1, verbose_name='饲养方式'),
        ),
    ]
