# Generated by Django 2.0.3 on 2019-06-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0024_yeartcjirouparam_nyear'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YearTCJirouParam',
            new_name='YearTaotaiJirouParam',
        ),
    ]
