# Generated by Django 2.0.3 on 2019-06-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0025_auto_20190627_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCoreTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('Year', models.IntegerField(verbose_name='年份')),
                ('WeekNum', models.IntegerField(verbose_name='周度')),
                ('startDate', models.DateField(verbose_name='开始日期')),
                ('endDate', models.DateField(verbose_name='结束日期')),
                ('TotalYuChengCunLan', models.IntegerField(verbose_name='总育成期存栏')),
                ('TotalChanDanCunLan', models.IntegerField(verbose_name='总产蛋期存栏')),
                ('TotalDan', models.IntegerField(verbose_name='总产蛋数')),
                ('TotalChuJi', models.IntegerField(verbose_name='雏鸡总数')),
                ('TotalFactSaleChuJi', models.IntegerField(verbose_name='实际销售雏鸡总数')),
                ('TaoTaiJiNum', models.IntegerField(verbose_name='淘汰鸡数目')),
                ('dTaoTaiJiRou', models.IntegerField(verbose_name='淘汰鸡肉')),
                ('nGeneration', models.IntegerField(verbose_name='代次')),
                ('nDraftOrOriginal', models.IntegerField(verbose_name='存储类型')),
                ('nBirdsType', models.IntegerField(verbose_name='家禽种类')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
