# Generated by Django 2.0.3 on 2019-06-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0026_weeklycoretable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycoretable',
            name='dTaoTaiJiRou',
            field=models.FloatField(verbose_name='淘汰鸡肉'),
        ),
    ]
