# Generated by Django 2.0.3 on 2019-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0028_weeklyintroducedmedian'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyintroducedmedian',
            name='shengchanZhou',
            field=models.IntegerField(default=1, verbose_name='生产周编号'),
        ),
    ]
