# Generated by Django 2.0.3 on 2019-07-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0030_auto_20190702_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyintroducedmedian',
            name='TotalChanDanCunLan',
            field=models.IntegerField(blank=True, null=True, verbose_name='产蛋期存栏'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedmedian',
            name='TotalChuJi',
            field=models.IntegerField(blank=True, null=True, verbose_name='鸡总数'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedmedian',
            name='TotalDan',
            field=models.IntegerField(blank=True, null=True, verbose_name='产蛋数'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedmedian',
            name='TotalYuChengCunLan',
            field=models.IntegerField(blank=True, null=True, verbose_name='育成期存栏'),
        ),
    ]
