# Generated by Django 2.0.3 on 2019-07-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0031_auto_20190703_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyintroducedmedian',
            name='originWeek',
            field=models.IntegerField(default=0, verbose_name='引种周度'),
        ),
        migrations.AddField(
            model_name='weeklyintroducedmedian',
            name='originYear',
            field=models.IntegerField(default=0, verbose_name='引种年份'),
        ),
    ]
