# Generated by Django 2.0.3 on 2019-07-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0032_auto_20190703_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyintroducedmedian',
            old_name='shengchanZhou',
            new_name='shengchanWeek',
        ),
    ]
