# Generated by Django 2.0.3 on 2019-07-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0033_auto_20190703_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducedinfodetail',
            name='huanyuRate',
            field=models.FloatField(default=0, verbose_name='强制换羽比例'),
        ),
        migrations.AddField(
            model_name='introducedinfodetail',
            name='qzhyFlag',
            field=models.IntegerField(default=0, verbose_name='是否强制换羽'),
        ),
    ]
