# Generated by Django 2.0.3 on 2019-07-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0034_auto_20190724_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducedinfodetail',
            name='qzhyPeriod',
            field=models.IntegerField(default=30, verbose_name='强制换羽周期'),
        ),
    ]
