# Generated by Django 2.0.3 on 2019-07-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0035_introducedinfodetail_qzhyperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesinfo',
            name='Generation',
            field=models.IntegerField(verbose_name='代次'),
        ),
    ]
