# Generated by Django 2.0.3 on 2019-07-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0036_auto_20190725_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesinfo',
            name='BirdType',
            field=models.IntegerField(verbose_name='家禽种类'),
        ),
    ]
