# Generated by Django 2.0.3 on 2019-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0037_auto_20190725_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducedinfodetail',
            name='qzhyStartWeek',
            field=models.IntegerField(default=0, verbose_name='强制换羽开始周'),
        ),
    ]
