# Generated by Django 2.0.3 on 2019-07-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0038_introducedinfodetail_qzhystartweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='QZHYweekStandardTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('WeekNum', models.IntegerField(verbose_name='生产周')),
                ('SpeciesId', models.IntegerField(default=1, verbose_name='品种')),
                ('feedWayId', models.IntegerField(default=1, verbose_name='饲养方式')),
                ('siTaoRate', models.FloatField(verbose_name='死淘率')),
                ('ChanDanRate', models.FloatField(verbose_name='产蛋率')),
                ('RuFuZhongDanRate', models.FloatField(verbose_name='入孵种蛋率')),
                ('ShouJingRate', models.FloatField(verbose_name='受精率')),
                ('FuHuaRate', models.FloatField(verbose_name='孵化率')),
                ('nGeneration', models.IntegerField(verbose_name='代次')),
                ('nBirdsType', models.IntegerField(verbose_name='家禽种类')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
