# Generated by Django 2.0.3 on 2019-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0039_qzhyweekstandardtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducedinfodetail',
            name='HuanyuInterval',
            field=models.IntegerField(default=0, verbose_name='强制换羽间隙'),
        ),
    ]
