# Generated by Django 2.0.3 on 2019-08-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0041_remove_introducedinfo_liveperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystatistictable',
            name='TotalChuLanRouJiNum',
            field=models.FloatField(verbose_name='出栏肉鸡总量'),
        ),
    ]
