# Generated by Django 2.0.3 on 2019-08-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0042_auto_20190807_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystatistictable',
            name='ChuLanRouJiNum35',
            field=models.FloatField(verbose_name='35日龄出栏肉鸡数量'),
        ),
        migrations.AlterField(
            model_name='weeklystatistictable',
            name='ChuLanRouJiNum42',
            field=models.FloatField(verbose_name='42日龄出栏肉鸡数量'),
        ),
        migrations.AlterField(
            model_name='weeklystatistictable',
            name='ChuLanRouJiNum49',
            field=models.FloatField(verbose_name='49日龄出栏肉鸡数量'),
        ),
        migrations.AlterField(
            model_name='weeklystatistictable',
            name='ChuLanRouJiNum56',
            field=models.FloatField(verbose_name='56日龄出栏肉鸡数量'),
        ),
        migrations.AlterField(
            model_name='weeklystatistictable',
            name='CunlLanNum35',
            field=models.FloatField(verbose_name='35日龄存栏量'),
        ),
        migrations.AlterField(
            model_name='weeklystatistictable',
            name='CunlLanNum42',
            field=models.FloatField(verbose_name='42日龄存栏量'),
        ),
        migrations.AlterField(
            model_name='weeklystatistictable',
            name='CunlLanNum49',
            field=models.FloatField(verbose_name='49日龄存栏量'),
        ),
        migrations.AlterField(
            model_name='weeklystatistictable',
            name='CunlLanNum56',
            field=models.FloatField(verbose_name='56日龄存栏量'),
        ),
    ]
