# Generated by Django 2.0.3 on 2019-08-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0043_auto_20190807_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyStatisticDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('Year', models.IntegerField(verbose_name='年份')),
                ('WeekNum', models.IntegerField(verbose_name='周度')),
                ('startDate', models.DateField(verbose_name='开始日期')),
                ('endDate', models.DateField(verbose_name='结束日期')),
                ('CunlLanNum35', models.FloatField(verbose_name='35日龄存栏量')),
                ('CunlLanNum42', models.FloatField(verbose_name='42日龄存栏量')),
                ('CunlLanNum49', models.FloatField(verbose_name='49日龄存栏量')),
                ('CunlLanNum56', models.FloatField(verbose_name='56日龄存栏量')),
                ('ChuLanRouJiNum35', models.FloatField(verbose_name='35日龄出栏肉鸡数量')),
                ('ChuLanRouJiNum42', models.FloatField(verbose_name='42日龄出栏肉鸡数量')),
                ('ChuLanRouJiNum49', models.FloatField(verbose_name='49日龄出栏肉鸡数量')),
                ('ChuLanRouJiNum56', models.FloatField(verbose_name='56日龄出栏肉鸡数量')),
                ('TotalChuLanRouJiNum', models.FloatField(verbose_name='出栏肉鸡总量')),
                ('HuoZhong35', models.FloatField(verbose_name='35日龄出栏肉鸡活重')),
                ('HuoZhong42', models.FloatField(verbose_name='42日龄出栏肉鸡活重')),
                ('HuoZhong49', models.FloatField(verbose_name='49日龄出栏肉鸡活重')),
                ('HuoZhong56', models.FloatField(verbose_name='56日龄出栏肉鸡活重')),
                ('TotalHuoZhong', models.FloatField(verbose_name='出栏肉鸡活重总量')),
                ('JiRou35', models.FloatField(verbose_name='35日龄出栏鸡肉重量')),
                ('JiRou42', models.FloatField(verbose_name='42日龄出栏鸡肉重量')),
                ('JiRou49', models.FloatField(verbose_name='49日龄出栏鸡肉重量')),
                ('JiRou56', models.FloatField(verbose_name='56日龄出栏鸡肉重量')),
                ('TotalJiRou', models.FloatField(verbose_name='出栏鸡肉总重量')),
                ('JiXiong35', models.FloatField(verbose_name='35日龄出栏鸡胸肉重量')),
                ('JiXiong42', models.FloatField(verbose_name='42日龄出栏鸡胸肉重量')),
                ('JiXiong49', models.FloatField(verbose_name='49日龄出栏鸡胸肉重量')),
                ('JiXiong56', models.FloatField(verbose_name='56日龄出栏鸡胸肉重量')),
                ('TotalJiXiong', models.FloatField(verbose_name='出栏鸡胸肉总重量')),
                ('JiChi35', models.FloatField(verbose_name='35日龄出栏鸡翅重量')),
                ('JiChi42', models.FloatField(verbose_name='42日龄出栏鸡翅重量')),
                ('JiChi49', models.FloatField(verbose_name='49日龄出栏鸡翅重量')),
                ('JiChi56', models.FloatField(verbose_name='56日龄出栏鸡翅重量')),
                ('TotalJiChi', models.FloatField(verbose_name='出栏鸡翅总重量')),
                ('JiTui35', models.FloatField(verbose_name='35日龄出栏鸡腿重量')),
                ('JiTui42', models.FloatField(verbose_name='42日龄出栏鸡腿重量')),
                ('JiTui49', models.FloatField(verbose_name='49日龄出栏鸡腿重量')),
                ('JiTui56', models.FloatField(verbose_name='56日龄出栏鸡腿重量')),
                ('TotalJiTui', models.FloatField(verbose_name='出栏鸡腿总重量')),
                ('JiGuJia35', models.FloatField(verbose_name='35日龄出栏鸡骨架重量')),
                ('JiGuJia42', models.FloatField(verbose_name='42日龄出栏鸡骨架重量')),
                ('JiGuJia49', models.FloatField(verbose_name='49日龄出栏鸡骨架重量')),
                ('JiGuJia56', models.FloatField(verbose_name='56日龄出栏鸡骨架重量')),
                ('TotalJiGuJia', models.FloatField(verbose_name='出栏鸡骨架总重量')),
                ('JiNeiZang35', models.FloatField(verbose_name='35日龄出栏鸡内脏重量')),
                ('JiNeiZang42', models.FloatField(verbose_name='42日龄出栏鸡内脏重量')),
                ('JiNeiZang49', models.FloatField(verbose_name='49日龄出栏鸡内脏重量')),
                ('JiNeiZang56', models.FloatField(verbose_name='56日龄出栏鸡内脏重量')),
                ('TotalJiNeiZang', models.FloatField(verbose_name='出栏鸡内脏总重量')),
                ('nDraftOrOriginal', models.IntegerField(verbose_name='存储类型')),
                ('nBirdsType', models.IntegerField(default=1, verbose_name='家禽种类')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='weeklystatistictable',
            name='nBirdsType',
            field=models.IntegerField(default=1, verbose_name='家禽种类'),
        ),
    ]
