# Generated by Django 2.0.3 on 2019-11-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0048_auto_20191101_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyIntroducedSumMedian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('originYear', models.IntegerField(default=0, verbose_name='引种年份')),
                ('originWeek', models.IntegerField(default=0, verbose_name='引种周度')),
                ('Year', models.IntegerField(verbose_name='年份')),
                ('WeekNum', models.IntegerField(verbose_name='周度')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('shengchanWeek', models.IntegerField(blank=True, default=1, null=True, verbose_name='生产周编号')),
                ('TotalYuChengCunLan', models.IntegerField(blank=True, null=True, verbose_name='育成期存栏')),
                ('TotalChanDanCunLan', models.IntegerField(blank=True, null=True, verbose_name='产蛋期存栏')),
                ('TotalDan', models.IntegerField(blank=True, null=True, verbose_name='产蛋数')),
                ('TotalChuJi', models.IntegerField(blank=True, null=True, verbose_name='鸡总数')),
                ('TotalFactSaleChuJi', models.IntegerField(blank=True, null=True, verbose_name='实际销售雏鸡总数')),
                ('TaoTaiJiNum', models.IntegerField(blank=True, null=True, verbose_name='淘汰鸡数目')),
                ('dTaoTaiJiRou', models.FloatField(blank=True, null=True, verbose_name='淘汰鸡肉')),
                ('nGeneration', models.IntegerField(blank=True, null=True, verbose_name='代次')),
                ('nDraftOrOriginal', models.IntegerField(blank=True, null=True, verbose_name='存储类型')),
                ('nBirdsType', models.IntegerField(blank=True, null=True, verbose_name='家禽种类')),
                ('Remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
