# Generated by Django 2.0.3 on 2019-11-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0049_weeklyintroducedsummedian'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyintroducedsummedian',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='计算标志'),
        ),
    ]
