# Generated by Django 2.0.3 on 2019-11-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0050_weeklyintroducedsummedian_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyintroducedsummedian',
            name='flag',
        ),
        migrations.AddField(
            model_name='introducedinfo',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='计算标志'),
        ),
    ]
