# Generated by Django 2.0.3 on 2019-11-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiyu', '0051_auto_20191101_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introducedinfo',
            name='RuSheNum',
            field=models.BigIntegerField(verbose_name='入舍量'),
        ),
        migrations.AlterField(
            model_name='weeklycoretable',
            name='TaoTaiJiNum',
            field=models.BigIntegerField(verbose_name='淘汰鸡数目'),
        ),
        migrations.AlterField(
            model_name='weeklycoretable',
            name='TotalChanDanCunLan',
            field=models.BigIntegerField(verbose_name='总产蛋期存栏'),
        ),
        migrations.AlterField(
            model_name='weeklycoretable',
            name='TotalChuJi',
            field=models.BigIntegerField(verbose_name='雏鸡总数'),
        ),
        migrations.AlterField(
            model_name='weeklycoretable',
            name='TotalDan',
            field=models.BigIntegerField(verbose_name='总产蛋数'),
        ),
        migrations.AlterField(
            model_name='weeklycoretable',
            name='TotalFactSaleChuJi',
            field=models.BigIntegerField(verbose_name='实际销售雏鸡总数'),
        ),
        migrations.AlterField(
            model_name='weeklycoretable',
            name='TotalYuChengCunLan',
            field=models.BigIntegerField(verbose_name='总育成期存栏'),
        ),
        migrations.AlterField(
            model_name='weeklycoretable',
            name='dTaoTaiJiRou',
            field=models.BigIntegerField(verbose_name='淘汰鸡肉'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedsummedian',
            name='TaoTaiJiNum',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='淘汰鸡数目'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedsummedian',
            name='TotalChanDanCunLan',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='产蛋期存栏'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedsummedian',
            name='TotalChuJi',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='鸡总数'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedsummedian',
            name='TotalDan',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='产蛋数'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedsummedian',
            name='TotalFactSaleChuJi',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='实际销售雏鸡总数'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedsummedian',
            name='TotalYuChengCunLan',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='育成期存栏'),
        ),
        migrations.AlterField(
            model_name='weeklyintroducedsummedian',
            name='dTaoTaiJiRou',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='淘汰鸡肉'),
        ),
    ]
